backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: FirstEvent, name: firstEvent, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: SecondEvent, name: secondEvent,   widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: ThirdEvent, name: thirdEvent, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}]}
  - name: "aboutUs"
    label: "AboutUs"
    files:
      - file: "src/pages/aboutus/index.md"
        label: "About Us Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-us-page"}
          - {label: MainHeader, name: mainHeader, widget: string}
          - {label: MainDescription1, name: mainDescription1, widget: string}
          - {label: MainDescription2, name: mainDescription2, widget: string}
          - {label: SubHeader, name: subHeader, widget: string}
          - {label: SubDescription, name: subDescription, widget: string}
          - {label: LinkName, name: linkName, widget: string}
          - {label: Link, name: link, widget: string}
          - {label: LastDescription, name: lastDescription, widget: string}
          - {label: FirstEvent, name: firstEvent, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: SecondEvent, name: secondEvent,   widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: ThirdEvent, name: thirdEvent, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}]}
  - name: "partner"
    label: "Partners"
    folder: "src/pages/partner"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "partner-post"}
      - {label: Name, name: name, widget: string}
      - {label: SubName, name: subName, widget: string, required: false}
      - {label: EstablishmentYear, name: establishmentYear, widget: number, required: false, default: 0}
      - {label: Slogan, name: slogan, widget: string, required: false}
      - {label: Introduction, name: introduction, widget: string, required: false}
      - {label: Location, name: location, widget: string, required: false}
      - {label: Email, name: email, widget: string, required: false}
      - {label: Homepage, name: homepage, widget: string, required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Logo, name: logo, widget: image, required: false}
  - name: "sponsor"
    label: "Sponsors"
    folder: "src/pages/sponsor"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "sponsor-post"}
      - {label: Name, name: name, widget: string}
      - {label: SubName, name: subName, widget: string, required: false}
      - {label: Department, name: dept, widget: string, required: false}
      - {label: EstablishmentYear, name: establishmentYear, widget: number, required: false, default: "number"}
      - {label: Slogan, name: slogan, widget: string, required: false}
      - {label: Introduction, name: introduction, widget: string, required: false}
      - {label: Location, name: location, widget: string, required: false}
      - {label: Email, name: email, widget: string, required: false}
      - {label: Homepage, name: homepage, widget: string, required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Logo, name: logo, widget: image, required: false}
  - name: "contact"
    label: "Contact"
    files:
      - file: "src/pages/contact/index.md"
        label: "Contact Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: MainHeader, name: mainHeader, widget: string}
          - {label: MainDescription1, name: mainDescription1, widget: string}
          - {label: MainDescription2, name: mainDescription2, widget: string}
          - {label: MainDescription3, name: mainDescription3, widget: string}
          - {label: SubHeader, name: subHeader, widget: string}
          - {label: FirstFAQ, name: firstFAQ, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description1, widget: text}, {label: Description, name: description2, widget: text}]}
          - {label: SecondFAQ, name: secondFAQ, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description1, widget: text}, {label: Description, name: description2, widget: text}]}
          - {label: ThirdFAQ, name: thirdFAQ, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description1, widget: text}, {label: Description, name: description2, widget: text}]}
          - {label: FourthFAQ, name: forthFAQ, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description1, widget: text}, {label: Description, name: description2, widget: text}]}
          - {label: FifthFAQ, name: fifthFAQ, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description1, widget: text}, {label: Description, name: description2, widget: text}]}
          - {label: SixthFAQ, name: sixthFAQ, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description1, widget: text}, {label: Description, name: description2, widget: text}]}
          - {label: LastComment1, name: lastComment1, widget: string}
          - {label: LastComment2, name: lastComment2, widget: string}