backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: FirstEvent, name: firstEvent, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: SecondEvent, name: secondEvent,   widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: ThirdEvent, name: thirdEvent, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: image}]}
  - name: "partner"
    label: "Partners"
    folder: "src/pages/partner"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "partner-post"}
      - {label: Name, name: name, widget: string}
      - {label: SubName, name: subName, widget: string}
      - {label: EstablishmentYear, name: establishmentYear, widget: number}
      - {label: Slogan, name: slogan, widget: string}
      - {label: Introduction, name: introduction, widget: string}
      - {label: Location, name: location, widget: string}
      - {label: Email, name: email, widget: string}
      - {label: Homepage, name: homepage, widget: string}
      - {label: Logo, name: logo, widget: image}
  - name: "sponsor"
    label: "Sponsors"
    folder: "src/pages/sponsor"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "sponsor-post"}
      - {label: Name, name: name, widget: string}
      - {label: SubName, name: subName, widget: string}
      - {label: Department, name: dept, widget: string}
      - {label: EstablishmentYear, name: establishmentYear, widget: number}
      - {label: Slogan, name: slogan, widget: string}
      - {label: Introduction, name: introduction, widget: string}
      - {label: Location, name: location, widget: string}
      - {label: Email, name: email, widget: string}
      - {label: Homepage, name: homepage, widget: string}
      - {label: Logo, name: logo, widget: image}